# Permalinks
relative_permalinks: false

# Setup
title:            Sean Purcell
tagline:          Software Engineer in Training
url:              http://seanp.xyz
baseurl:          /
author:
  name:           Sean Purcell
  email:          me@seanp.xyz

# Custom vars
version:          1.0.0

pages_list:
  Projects: '/projects'
  Resume: '/resume.pdf'

github:           https://github.com/iburinoc
email:            me@seanp.xyz
highlighter:      pygments
